# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
#code here
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
two_d = arr.reshape(3,4)
two_d


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#Concatenation
import numpy as np

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

hor = np.hstack([a1, a2])
print(hor)

vert = np.vstack([a1, a2])
print(vert)



[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [2]:
#code here
import nltk
from nltk.corpus import stopwords
import string


def classify_emails(emails):
  imp_mail = []
  promo_emails = []
  spam_emails = []

  important_keywords = ["urgent", "important", "meeting", "deadline", "invoice"]
  promotion_keywords = ["sale", "discount", "offer", "coupon", "deal", "free"]
  spam_keywords = ["viagra", "casino", "free money", "click here", "unsubscribe"]

  for email in emails:
    cleaned_email = preprocess_email(email)

    if any(word in cleaned_email for word in important_keywords):
      imp_mail.append(email)
      continue
    if any(word in cleaned_email for word in promotion_keywords):
      promo_emails.append(email)
      continue

    if any(word in cleaned_email for word in spam_keywords) or has_spam_patterns(cleaned_email):
      spam_emails.append(email)
      continue
    else:
      print(f"Email '{email}' doesn't fit any category. Manually review it.")

  return imp_mail, promo_emails, spam_emails

def preprocess_email(email):
  email = email.lower()
  email = email.translate(str.maketrans('', '', string.punctuation))
  words = nltk.word_tokenize(email)
  stop_words = set(stopwords.words('english'))
  words = [word for word in words if word not in stop_words]
  processed_email = ' '.join(words)
  return processed_email

def has_spam_patterns(email):
  if email.upper() == email and len(email) > 50:
    return True
  if email.count('!') >= 3:
    return True

emails = ["Important meeting tomorrow!", "50% off sale on shoes!", "Free money! Click here to claim!"]
important, promotions, spam = classify_emails(emails)

print("Important emails:", important)
print("Promotions emails:", promotions)
print("Spam emails:", spam)


Important emails: ['Important meeting tomorrow!']
Promotions emails: ['50% off sale on shoes!', 'Free money! Click here to claim!']
Spam emails: []


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [3]:
#code here
eng_to_esp = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "you're welcome": "de nada",
    "apple": "manzana",
    "computer": "computadora",
    "book": "libro",
    "water": "agua",
    "fire": "fuego",
    "earth": "tierra",
    "air": "aire",
}
while True:
    eng_word = input("Enter an English word (or 'exit' to quit): ").lower()
    if eng_word in eng_to_esp:
        esp_trans = eng_to_esp[eng_word]
        print(f"Spanish translation: {esp_trans}")
    elif eng_word == "quit":
        break
    else:
        print(f"Translation for '{eng_word}' not available.")

print("Exiting the dictionary...")


Spanish translation: adiós
Exiting the dictionary...


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [2]:
import pandas as pd
file = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
data = pd.read_csv(file)
df = pd.DataFrame(data)
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [19]:
#Calculate the total global sales for all games in the dataset.
total_globalSales = df['Global_Sales'].sum()
print("Total Global Sales are: ",total_globalSales)

Total Global Sales are:  8920.44


In [36]:
#Find the game with the highest global sales.
sales =  df[df['Global_Sales'].notna()]
highest_game = sales.loc[sales['Global_Sales'].idxmax()]

print(f"Game with the highest global sales:")
print(f"Name: {highest_game['Name']}")

Game with the highest global sales:
Name: Wii Sports


In [42]:
# Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales
NA_mean =df.NA_Sales.mean()
print("Average of this NA_sales is: ",NA_mean)

EU_mean =df.EU_Sales.mean()
print("Average of this EU_sales is: ",EU_mean)

JP_mean =df.JP_Sales.mean()
print("Average of this JP_sales is: ",JP_mean)

others_mean =df.Other_Sales.mean()
print("Average of this others_sales is: ",others_mean)

Average of this NA_sales is:  0.26466742981082064
Average of this EU_sales is:  0.14665200626581515
Average of this JP_sales is:  0.077781660441017
Average of this others_sales is:  0.0480630196409206


In [47]:
five_game = df.sort_values(by = "Global_Sales", ascending = False).head()
five_game
fiv =pd.DataFrame(five_game['Genre'])
fiv


Genre
0        Sports
1      Platform
2        Racing
3        Sports
4  Role-Playing

In [7]:
# Calculate total sales per genre
genre_sales = df.groupby("Genre")[
    ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]
].sum()
# Most popular genre in North America
most_popular_na = genre_sales["NA_Sales"].idxmax()
print(f"Most popular genre in North America: {most_popular_na}")
print("\nTotal sales for each genre across regions:")
print(genre_sales)

Most popular genre in North America: Action

Total sales for each genre across regions:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [8]:
# Display last 10 rows of genre_region_sales
print("Last 10 rows of genre_region_sales:")
print(genre_sales.tail(10))

Last 10 rows of genre_region_sales:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [9]:
# Top 3 platforms with highest global sales
top_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print(f"\nTop 3 platforms with highest global sales:{top_platforms}")



Top 3 platforms with highest global sales:Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [10]:
# Market share for each genre
genre_market_share = (genre_sales.sum(axis=1) / df['Global_Sales'].sum()) * 100
print(f"\nMarket share for each genre:\n{genre_market_share}")



Market share for each genre:
Genre
Action          19.619660
Adventure        2.677110
Fighting         5.032711
Misc             9.072422
Platform         9.316132
Puzzle           2.739999
Racing           8.203295
Role-Playing    10.394779
Shooter         11.623193
Simulation       4.393393
Sports          14.915632
Strategy         1.960217
dtype: float64


In [11]:
# Correlation coefficient between NA_Sales and EU_Sales
correlation = df['NA_Sales'].corr(df['EU_Sales'])
print(f"\nCorrelation coefficient between NA_Sales and EU_Sales: {correlation:.2f}")


Correlation coefficient between NA_Sales and EU_Sales: 0.77


In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
